language: ruby
rvm:
  - 2.0.0p247
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - mysql -e 'create database onemdl_test'
  - psql -c 'create database onemdl_test' -U postgres
